const constant = {
    USER_ROOT: 'root',
    USER_BGD: 'bgd',
    REDIS_PREFIX_ACCESS_TOKEN: 'ACCESS_TOKEN',
    REDIS_PREFIX_PERMISSION: 'PERMISSION',
    ROLES: {
        BGD: '684927c871287f2ae7d8130a',
        admin: '684927c871287f2ae7d8130b',
        warehouseStaff: '684927c871287f2ae7d8130c',
        warehouseAccountant: '684927c871287f2ae7d8130e',
        debtAccountant: '684927c871287f2ae7d8130f',
        billAccountant: '684927c871287f2ae7d81310',
        sale: '684927c871287f2ae7d81311',
    },
    PRODUCT_MANAGEMENT_TYPE: {
        NONE: 'none',
        SERIAL: 'serial',
        BATCH: 'batch',
    },
    GOODS_ISSUE_STATUS: {
        NULL: '',
        DRAFT: 'draft',
        WAREHOUSE_STAFF_APPROVAL: 'warehouseStaffApproval',
        WAREHOUSE_ACCOUNTANT_APPROVAL: 'warehouseAccountantApproval',
        DEBT_ACCOUNTANT_APPROVAL: 'debtAccountantApproval',
        BILL_ACCOUNTANT_APPROVAL: 'billAccountApproval',
        APPROVED: 'approved',
        REJECT: 'reject',
        CANCEL: 'cancel',
    },
    GOODS_RECEIPT_STATUS: {
        NULL: '',
        WAREHOUSE_STAFF_APPROVAL: 'warehouseStaffApproval',
        APPROVED: 'approved',
        REJECT: 'reject',
        CANCEL: 'cancel',
    },
    GOODS_ADVANCE_STATUS: {
        NULL: '',
        WAREHOUSE_STAFF_APPROVAL: 'warehouseStaffApproval',
        APPROVED: 'approved',
        WAITING_FOR_EXTENSION: 'waitingForExtension',
        REJECT: 'reject',
        CANCEL: 'cancel',
    },
    GOODS_ADVANCE_PROCESS_TITLE: {
        CREATE: 'create',
        APPROVAL: 'approval',
        EXTEND: 'extend',
        CANCEL: 'cancel',
    },
    APPROVAL_STATUS: {
        NULL: '',
        APPROVED: 'approved',
        REJECTED: 'rejected',
        CANCEL: 'cancel',
    },
    PAYMENT_STATUS: {
        PAID: 'paid',
        PARTIALLY_PAID: 'partiallyPaid',
    },
    PAYMENT_METHOD: {
        CASH: 'cash',
        BANK_TRANSFER: 'bankTransfer',
        CREDIT_CARD: 'creditCard',
        MOBILE_PAYMENT: 'mobilePayment',
        OTHER: 'other',
    },
    DISCOUNT_TYPE: {
        PERCENTAGE: 'percentage',
        AMOUNT: 'amount',
    },
    DEBT_REMINDER_STATUS: {
        NULL: '',
        PENDING: 'scheduled',
        SENT: 'completed',
        OVERDUE: 'late',
        PAID: 'paid',
    },
    DEBT_REMINDER_METHOD: {
        NULL: '',
        EMAIL: 'email',
        PHONE: 'phone',
        OFFLINE: 'offline',
    },
    INVOICE_STATUS: {
        NULL: '',
        PAID: 'paid',
        PARTIALLY_PAID: 'partiallyPaid',
        PENDING: 'pending',
        OVERDUE: 'overdue',
    },
}

module.exports = constant
