const express = require('express')
const router = express.Router()

const authRoute = require('./authRoute')
const userRoute = require('./userRoute')
const supplierRoute = require('./supplierRoute')

const warehouseRoute = require('./warehousesRoute')
const uploadRoute = require('./uploadRoute')
const productCategoryRoute = require('./productCategoryRoute')
const customerRoute = require('./customerRoute')
const brandRoute = require('./brandRoute')
const productRoute = require('./productRoute')
const goodsReceiptRoute = require('./goodsReceiptRoute')
const goodsIssueRoute = require('./goodsIssueRoute')
const goodsAdvanceRoute = require('./goodsAdvanceRoute')
const invoiceRoute = require('./invoiceRoute')
const discountRoute = require('./discountRoute')
const paymentHistoryRoute = require('./paymentHistoryRoute')

router.use('/auth', authRoute)
router.use('/user', userRoute)
router.use('/supplier', supplierRoute)
router.use('/warehouse', warehouseRoute)
router.use('/upload', uploadRoute)
router.use('/productCategory', productCategoryRoute)
router.use('/customer', customerRoute)
router.use('/brand', brandRoute)
router.use('/product', productRoute)
router.use('/goodsReceipt', goodsReceiptRoute)
router.use('/goodsIssue', goodsIssueRoute)
router.use('/goodsAdvance', goodsAdvanceRoute)
router.use('/invoice', invoiceRoute)
router.use('/discount', discountRoute)
router.use('/paymentHistory', paymentHistoryRoute)

module.exports = router
