const express = require('express')
const router = express.Router()

const authRoute = require('./authRoute')
const userRoute = require('./userRoute')
const supplierRoute = require('./supplierRoute')
const warehouseRoute = require('./warehousesRoute')
const uploadRoute = require('./uploadRoute')
const productCategoryRoute = require('./productCategoryRoute')
const customerRoute = require('./customerRoute')
const brandRoute = require('./brandRoute')
const productRoute = require('./productRoute')
const goodsReceiptRoute = require('./goodsReceiptRoute')
const goodsIssueRoute = require('./goodsIssueRoute')
const goodsAdvanceRoute = require('./goodsAdvanceRoute')
const invoiceRoute = require('./invoiceRoute')
const discountRoute = require('./discountRoute')
const paymentHistoryRoute = require('./paymentHistoryRoute')
const debtRoute = require('./debtRoute')
const configDebtRoute = require('./configDebtRoute')
const debtReminderRoute = require('./debtReminderRoute')
const reportsRoute = require('./reportsRoute')
const dashBoardRoute = require('./dashBoardRoute')
const systemRoute = require('./systemRoute')
const mailRoute = require('./mailRoute')
const productTransferHistoryRoute = require('./productTransferHistoryRoute')
const workOrderRoute = require('./workOrderRoute')
const technicianRoute = require('./technicianRoute')
const orderRoute = require('./orderRoute')
const machineSettingRoute = require('./machineSettingRoute')
const workOrderDetailRoute = require('./workOrderDetailRoute')
const contactPersonCustomerRoute = require('./contactPersonCustomerRoute')
const contractRoute = require('./contractRoute')
const machineProperyRoute = require('./machinePropertyRoute')
// const printExcelRoute = require('./printExcel')
const previousDebtRoute = require('./previousDebt')

router.use('/auth', authRoute)
router.use('/user', userRoute)
router.use('/supplier', supplierRoute)
router.use('/warehouse', warehouseRoute)
router.use('/upload', uploadRoute)
router.use('/productCategory', productCategoryRoute)
router.use('/customer', customerRoute)
router.use('/brand', brandRoute)
router.use('/product', productRoute)
router.use('/goodsReceipt', goodsReceiptRoute)
router.use('/goodsIssue', goodsIssueRoute)
router.use('/goodsAdvance', goodsAdvanceRoute)
router.use('/invoice', invoiceRoute)
router.use('/discount', discountRoute)
router.use('/paymentHistory', paymentHistoryRoute)
router.use('/debt', debtRoute)
router.use('/configDebt', configDebtRoute)
router.use('/debtReminder', debtReminderRoute)
router.use('/reports', reportsRoute)
router.use('/dashboard', dashBoardRoute)
router.use('/system', systemRoute)
router.use('/mail', mailRoute)
router.use('/productTransferHistory', productTransferHistoryRoute)
router.use('/order', orderRoute)
router.use('/workOrder', workOrderRoute)
router.use('/technician', technicianRoute)
router.use('/machineSetting', machineSettingRoute)
router.use('/workOrderDetail', workOrderDetailRoute)
router.use('/contactPerson', contactPersonCustomerRoute)
router.use('/contract', contractRoute)
router.use('/machinePropery', machineProperyRoute)
// router.use('/printExcel', printExcelRoute)
router.use('/previousDebt', previousDebtRoute)

module.exports = router
