const { Types } = require('mongoose')
const { logger } = require('../config/loggerConfig')
const MachinePropertiesModel = require('../models/machineProperties')
const constant = require('../utils/constant/constant')

async function machinePropertiesSeeder() {
    await MachinePropertiesModel.deleteMany({})
    await MachinePropertiesModel.insertMany([
        //info
        {
            _id: new Types.ObjectId('69081ac30879097d22c84abe'),
            name: 'Loại mực',
            type: 'linked',
            categoryLinkedName: constant.CATEGORY_NAME.MATERIAL_INK,
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6909cccb681d4e170abadbd2'),
            name: 'Loại ruy băng',
            type: 'linked',
            categoryLinkedName: constant.CATEGORY_NAME.MATERIAL_RIBBON,
            group: 'info',
        },
        {
            _id: new Types.ObjectId('691508159d647f9729da4a9c'),
            name: 'Số lượng đầu in',
            type: 'custom',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a340'),
            name: 'Số Series Controller',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a341'),
            name: 'Số series Laser head',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a342'),
            name: 'Thời gian Controller',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a343'),
            name: 'Thời gian Laser head',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a344'),
            name: 'Ngày lắp đặt',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a345'),
            name: 'Số đầu đơn',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a346'),
            name: 'Số đầu ghép',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a347'),
            name: 'Bộ cấp mực',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a348'),
            name: 'Số Series máy',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a349'),
            name: 'Hướng đầu in',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34a'),
            name: 'Thời gian máy',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34b'),
            name: 'Kích thước nhãn',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34c'),
            name: 'Kính thước Pad',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34d'),
            name: 'Tốc độ chuyền',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34e'),
            name: 'Loại tay dán',
            type: 'custom',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a34f'),
            name: 'Thời gian mở máy',
            type: 'normal',
            group: 'info',
        },
        {
            _id: new Types.ObjectId('6915331a7df850bd0928a350'),
            name: 'Thời gian in phun',
            type: 'normal',
            group: 'info',
        },
        //spec
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c76798'),
            name: 'Scanhead Type',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c76799'),
            name: 'Focus',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679a'),
            name: 'Laser cooling type',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679b'),
            name: 'Live Movement',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679c'),
            name: 'Encoder Source',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679d'),
            name: 'Encoder Scale',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679e'),
            name: 'Encoder Delay',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c7679f'),
            name: 'Product detect ignore distance',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a0'),
            name: 'Laser Power',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a1'),
            name: 'Jump Speed',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a2'),
            name: 'Coding Speed',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a3'),
            name: 'Max Vector Length',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a4'),
            name: 'Software Version',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a5'),
            name: 'Software Type',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a6'),
            name: 'Chế độ máy in',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a7'),
            name: 'Loại đầu in',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a8'),
            name: 'Chiều cao đầu in',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767a9'),
            name: 'Điện trở đầu in',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767aa'),
            name: 'Nhiệt độ đầu in',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ab'),
            name: 'Tương phản',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ac'),
            name: 'Áp lực đầu in',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ad'),
            name: 'Giới hạn rút về',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ae'),
            name: 'Preheart',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767af'),
            name: 'Tốc độ in',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b0'),
            name: 'Chế độ tay dán',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b1'),
            name: 'Khoảng cách nhỏ nhất giữa 2 sản phẩm',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b2'),
            name: 'Số nhãn trên từng sản phẩm',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b3'),
            name: 'Tín hiệu in',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b4'),
            name: 'Tín hiệu dán',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b5'),
            name: 'Áp suất khí nén',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b6'),
            name: 'Khoảng hở pad đến cạnh nhãn',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b7'),
            name: 'ACC firware version',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b8'),
            name: 'ACC Bootloader Version',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767b9'),
            name: 'Hướng lắp đặt',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ba'),
            name: 'Tính năng khác',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767bb'),
            name: 'Nồng độ chuẩn',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767bc'),
            name: 'Nồng độ hiện hành',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767bd'),
            name: 'Áp suất chuẩn',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767be'),
            name: 'Áp suất hiện hành',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767bf'),
            name: 'Tốc độ bơm',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c0'),
            name: 'Áp suất chân không',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c1'),
            name: 'Áp suất thu hổi',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c2'),
            name: 'Béc phun',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c3'),
            name: 'Charge level',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c4'),
            name: 'Mức giọt mực',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c5'),
            name: 'Loại mức giọt mực',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c6'),
            name: 'BUP time',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c7'),
            name: 'Nhiệt độ mực',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c8'),
            name: 'Thời gian ITM',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767c9'),
            name: 'Phiên bản phần mềm',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ca'),
            name: 'Chiều dài ống đầu phun',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767cb'),
            name: 'Ngôn ngữ',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767cc'),
            name: 'Thời gian pum',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767cd'),
            name: 'Pum thu hồi',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767ce'),
            name: 'Nhiệt độ môi trường',
            type: 'normal',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767cf'),
            name: 'Đầu phun',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d0'),
            name: 'Hình thức lắp đặt',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d1'),
            name: 'Nguồn điện',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d2'),
            name: 'Tiếp Max',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d3'),
            name: 'Môi trường đặt máy',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d4'),
            name: 'Chất liệu bao bì',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d5'),
            name: 'Tốc độ',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d6'),
            name: 'Độ nhám',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d7'),
            name: 'Nét chữ',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d8'),
            name: 'Nhu cầu khách hàng',
            type: 'custom',
            group: 'specs',
        },
        {
            _id: new Types.ObjectId('69153bd1fe55c7d502c767d9'),
            name: 'Linh kiện đi kèm',
            type: 'custom',
            group: 'specs',
        },
    ])
    logger.info('MachineProperties seeded')
}
module.exports = machinePropertiesSeeder
