// src/validations/customerValidation.js --- IMPROVED AND DETAILED

const joi = require('joi')

// Reusable sub-schemas, copied from supplierValidation.js for consistency
const contactPersonSchema = joi.object({
    name: joi.string().required().messages({
        'string.empty': 'Tên người liên hệ là bắt buộc',
        'any.required': 'Tên người liên hệ là bắt buộc',
    }),
    phone: joi
        .string()
        .pattern(/^[0-9]{10,15}$/)
        .required()
        .messages({
            'string.empty': 'Số điện thoại người liên hệ là bắt buộc',
            'string.pattern.base': 'Số điện thoại phải có từ 10 đến 15 chữ số',
            'any.required': 'Số điện thoại người liên hệ là bắt buộc',
        }),
})

const deliveryAddressSchema = joi.object({
    street: joi.string().required().messages({
        'string.empty': 'Tên đường là bắt buộc',
        'any.required': 'Tên đường là bắt buộc',
    }),
    ward: joi.string().required().messages({
        'string.empty': 'Phường/Xã là bắt buộc',
        'any.required': 'Phường/Xã là bắt buộc',
    }),
    district: joi.string().required().messages({
        'string.empty': 'Quận/Huyện là bắt buộc',
        'any.required': 'Quận/Huyện là bắt buộc',
    }),
    city: joi.string().required().messages({
        'string.empty': 'Thành phố là bắt buộc',
        'any.required': 'Thành phố là bắt buộc',
    }),
    country: joi.string().required().messages({
        'string.empty': 'Quốc gia là bắt buộc',
        'any.required': 'Quốc gia là bắt buộc',
    }),
})

const representativeSchema = joi.object({
    name: joi.string().required().messages({
        'string.empty': 'Tên người đại diện là bắt buộc',
        'any.required': 'Tên người đại diện là bắt buộc',
    }),
    title: joi.string().required().messages({
        'string.empty': 'Chức danh người đại diện là bắt buộc',
        'any.required': 'Chức danh người đại diện là bắt buộc',
    }),
    phone: joi
        .string()
        .pattern(/^[0-9]{10,15}$/)
        .required()
        .messages({
            'string.empty': 'Số điện thoại người đại diện là bắt buộc',
            'string.pattern.base': 'Số điện thoại phải có từ 10 đến 15 chữ số',
            'any.required': 'Số điện thoại người đại diện là bắt buộc',
        }),
})

const customerBaseSchema = {
    // The 'type' field is removed, as it's not in your customer model.
    // The 'code' (MKH) field is generated by the service, so it is not validated here.
    name: joi.string().required().messages({
        'string.empty': 'Tên là bắt buộc',
        'any.required': 'Tên là bắt buộc',
    }),
    officialName: joi.string().required().messages({
        'string.empty': 'Tên đầy đủ là bắt buộc',
        'any.required': 'Tên đầy đủ là bắt buộc',
    }),
    taxCode: joi
        .string()
        .pattern(/^[0-9]{10,15}$/)
        .required()
        .messages({
            'string.empty': 'Mã số thuế là bắt buộc',
<<<<<<< HEAD
            'string.pattern.base':
                'Mã số thuế phải là chữ số và có từ 10-15 ký tự',
=======
            'string.pattern.base': 
            'Mã số thuế phải là chữ số và có từ 10-15 ký tự',
>>>>>>> 7cce48f58ffbf5295c11b2fbd118b0eb09bf7f71
            'any.required': 'Mã số thuế là bắt buộc',
        }),
    fax: joi.string().allow('', null),
    email: joi
        .string()
        .email({ tlds: { allow: false } })
        .allow('', null),
    phone: joi
        .string()
        .pattern(/^[0-9]{10,15}$/)
        .allow('', null)
        .messages({
            'string.pattern.base': 'Số điện thoại phải có từ 10 đến 15 chữ số',
        }),
    billingAddress: joi.string().required().messages({
        'string.empty': 'Địa chỉ xuất hóa đơn là bắt buộc',
        'any.required': 'Địa chỉ xuất hóa đơn là bắt buộc',
    }),
    garageAddress: joi.string().allow('', null),
    deliveryAddresses: joi
        .array()
        .items(deliveryAddressSchema)
        .min(1)
        .max(5)
        .required()
        .messages({
            'array.min': 'Phải có ít nhất 1 địa chỉ giao hàng',
            'array.max': 'Không được nhiều hơn 5 địa chỉ giao hàng',
            'any.required': 'Danh sách địa chỉ giao hàng là bắt buộc',
        }),
    representative: representativeSchema.required(),
    contactPersons: joi.object({
        warehouseAccountant: joi.array().items(contactPersonSchema),
        sale: joi.array().items(contactPersonSchema),
        accountant: joi.array().items(contactPersonSchema),
        tech: joi.array().items(contactPersonSchema),
        debtAccountant: joi.array().items(contactPersonSchema),
        billAccountant: joi.array().items(contactPersonSchema),
    }),
    notes: joi.string().allow('', null),
    purchaseCycleInWeeks: joi.number().allow(null),
    internalTransport: joi.boolean().default(false),
    productsInUse: joi.array().items(joi.string()),
    status: joi.string().valid('none', 'met', 'not_met').default('none'),
    isActive: joi.boolean().default(true),
}

// The final validation object, ready for export.
const customerValidation = {
    create: {
        body: joi.object({
            ...customerBaseSchema,
        }),
    },
    // We can also prepare the 'update' validation for when you build that feature.
    update: {
        body: joi.object({
            ...customerBaseSchema,
            // 'code' is the unique customer ID and should never be changed.
<<<<<<< HEAD
            code: joi.forbidden(),
=======
            code: joi.forbidden(), 
>>>>>>> 7cce48f58ffbf5295c11b2fbd118b0eb09bf7f71
        }),
    },
}

<<<<<<< HEAD
module.exports = customerValidation
=======
module.exports = customerValidation
>>>>>>> 7cce48f58ffbf5295c11b2fbd118b0eb09bf7f71
